project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

